




version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: p
      POSTGRES_DB: data
    # ports:
      # - \"1111:5432\"


